### ISSUE TITLE
name 'coordinator' is not defined

### ISSUE THREAD

**Issue by fxxer** [rootnegativ1/unifi-wifi#2]
Latest few versions stopped working for me. I tried to change passoword via service call and got an error "name 'coordinator' is not defined"

I also added managed_aps which I did not have before. But it doesn't matter it stopped working. I did not change username or password and I am using local account on UDM-Pro with site-admin role.

```
- name: Home
  host: !secret unifi_wifi_url
  username: !secret unifi_wifi_username
  password: !secret unifi_wifi_password
  site: default
  scan_interval: 300
  unifi_os: true
  verify_ssl: false
  managed_aps:
    - name: U6-LR - Downstairs
      mac: !secret unifi_wifi_mac1
    - name: U6-LR - Upstairs
      mac: !secret unifi_wifi_mac2
  monitored_ssids:
    - name: !secret unifi_wifi_monitored_ssids_name1
```

Error messsage:
```
This error originated from a custom integration.

Logger: homeassistant.helpers.script.websocket_api_script
Source: custom_components/unifi_wifi/__init__.py:162
Integration: Unifi Wifi (documentation, issues)
First occurred: 08:11:18 (3 occurrences)
Last logged: 08:13:02

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: name 'coordinator' is not defined
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 703, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 665, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 1974, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2011, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/unifi_wifi/__init__.py", line 223, in random_password_service
    ind = _coordinator_index(coordinator)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/unifi_wifi/__init__.py", line 162, in _coordinator_index
    raise ValueError(f"The coordinator {coordinator} is not configured in YAML")
                                        ^^^^^^^^^^^
NameError: name 'coordinator' is not defined

```

**Comment by rootnegativ1** [comment]
A couple things:

- First: a code error on my part in the ValueError line. It should be: ```raise ValueError(f"The coordinator {name} is not configured in YAML")```. I'll push a fix for that shortly.
- Second: encountering that specific error means something is weird about the service call you're making.

Please paste the YAML block where you call ```unifi_wifi.random_password```. There may be a glitch having to do with the ```name``` key.

**Comment by fxxer** [comment]
Here it is:

```
service: unifi_wifi.random_password
data:
  name: default
  method: char
  char_count: 15
  ssid: Instant-WiFi
```

**Comment by rootnegativ1** [comment]
Change the name key to match your YAML config:
```yaml
service: unifi_wifi.random_password
data:
  name: Home
  method: char
  char_count: 15
  ssid: Instant-WiFi
```

**Comment by fxxer** [comment]
That helped, it works. I also have a problem with disable wifi, here's the call and error.

```
service: unifi_wifi.enable_wlan
data:
  name: Home
  ssid: Instant-WiFi
  enabled: false
```

```
This error originated from a custom integration.

Logger: homeassistant.helpers.script.websocket_api_script
Source: custom_components/unifi_wifi/__init__.py:170
Integration: Unifi Wifi (documentation, issues)
First occurred: 20:26:31 (4 occurrences)
Last logged: 21:45:56

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 703, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 665, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 1974, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2011, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/unifi_wifi/__init__.py", line 243, in enable_wlan_service
    if _validate_ssid(coordinator, ssid):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/unifi_wifi/__init__.py", line 170, in _validate_ssid
    hass.add_job(coordinators[ind].async_request_refresh())
                 ~~~~~~~~~~~~^^^^^
TypeError: list indices must be integers or slices, not str

```

**Comment by rootnegativ1** [comment]
ahh typos.; my nemesis. I'll push a new version.
